/**:
  ros__parameters:
    joints_map:
      left_front:
        - left_front_hip_joint
        - left_front_knee_joint
        - left_front_ankle_joint
        - left_front_foot_joint

      right_front:
        - right_front_hip_joint
        - right_front_knee_joint
        - right_front_ankle_joint
        - right_front_foot_joint

      left_hind:
        - left_rear_hip_joint
        - left_rear_knee_joint
        - left_rear_ankle_joint
        - left_rear_foot_joint

      right_hind:
        - right_rear_hip_joint
        - right_rear_knee_joint
        - right_rear_ankle_joint
        - right_rear_foot_joint
